name: Build and Deploy

on:
  push:
    branches:
      - deploy

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2  
      - name: Set up Node.js
        uses: actions/setup-node@v3  
        with:
          node-version: '18' 
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build -- --configuration production 
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/gespana  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/gespana
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v2.2.1  
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
